INSERT INTO cleanup 
  (role)
VALUES
  ('accounting assistant'),
  ('accounting assistant'),
  ('accounting assistant'),
  ('additional adr mixer'),
  ('additional adr mixer'),
  ('additional adr recordist'),
  ('additional adr recordist'),
  ('additional animal wrangler'),
  ('additional second assistant camera'),
  ('adr editor'),
  ('adr editor'),
  ('adr mixer'),
  ('adr recordist'),
  ('adr supervisor'),
  ('adr voice casting'),
  ('adr voice'),
  ('aerial coordinator Thanks'),
  ('animal trainer'),
  ('apprentice editor'),
  ('art department assistant'),
  ('assistant art director'),
  ('assistant music editor'),
  ('assistant office coordinator'),
  ('assistant production accountant'),
  ('assistant sound editor'),
  ('assistant sound editor'),
  ('assistant sound editor'),
  ('assistant: Frank Darabont'),
  ('assistant: Morgan Freeman'),
  ('assistant: Niki Marvin'),
  ('assistant: Tim Robbins'),
  ('background casting assistant'),
  ('background casting intern'),
  ('background casting'),
  ('best boy electric'),
  ('best boy grip'),
  ('boom operator'),
  ('cable person'),
  ('carpenter Sound Department'),
  ('carpenter'),
  ('casting assistant'),
  ('casting: Ohio'),
  ('caterer'),
  ('caterer'),
  ('caterer'),
  ('color timer'),
  ('colorist: mastering Location Management'),
  ('concertmaster'),
  ('conductor'),
  ('construction coordinator'),
  ('construction foreman'),
  ('costumer'),
  ('costumer'),
  ('craft service'),
  ('craft service'),
  ('craft service'),
  ('decorating consultant'),
  ('dolly grip'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('driver'),
  ('electric rigger'),
  ('electric rigger'),
  ('electrician'),
  ('executive music producer'),
  ('executive music producer'),
  ('exotic instruments'),
  ('extras casting assistant Costume and Wardrobe Department'),
  ('film loader'),
  ('first aid'),
  ('first assistant camera'),
  ('first assistant camera'),
  ('first assistant director'),
  ('first assistant editor'),
  ('foley artist'),
  ('foley artist'),
  ('foley artist'),
  ('foley artist'),
  ('foley mixer'),
  ('foley mixer'),
  ('foley recordist Special Effects by'),
  ('foley recordist'),
  ('gaffer'),
  ('grip'),
  ('grip'),
  ('grip'),
  ('grip'),
  ('grip'),
  ('grip'),
  ('grip'),
  ('gyrosphere assistant'),
  ('gyrosphere assistant'),
  ('gyrosphere operator'),
  ('hair stylist'),
  ('hair stylist'),
  ('helicopter pilot'),
  ('in memory of'),
  ('key carpenter'),
  ('key costumer Editorial Department'),
  ('key costumer'),
  ('key grip'),
  ('key hair stylist'),
  ('key makeup artist'),
  ('key second assistant director'),
  ('labor foreman'),
  ('labor gang boss'),
  ('lamp operator'),
  ('lamp operator'),
  ('lamp operator'),
  ('lamp operator'),
  ('lead person'),
  ('lighting stand-in'),
  ('lighting stand-in'),
  ('lighting stand-in'),
  ('lighting stand-in'),
  ('lighting stand-in'),
  ('lighting stand-in'),
  ('lighting stand-in'),
  ('location assistant Music Department'),
  ('location assistant'),
  ('location manager'),
  ('makeup artist Production Management'),
  ('makeup artist'),
  ('Makeup Department'),
  ('mixing recordist'),
  ('mixing recordist'),
  ('music consultant'),
  ('music contractor'),
  ('music copyist'),
  ('music copyist'),
  ('music editor'),
  ('music preparation'),
  ('music preparation'),
  ('music preparation'),
  ('music scoring mixer'),
  ('musician: French horn Transportation Department'),
  ('musician: harmonica'),
  ('musician: oboe soloist'),
  ('office assistant'),
  ('office intern'),
  ('on-set dresser'),
  ('orchestrator'),
  ('paint foreman'),
  ('paint gang boss'),
  ('paint gang boss'),
  ('painter'),
  ('painter'),
  ('picture car coordinator Other crew'),
  ('plasterer'),
  ('poster artist'),
  ('press attache: France'),
  ('production accountant'),
  ('production assistant'),
  ('production assistant'),
  ('production office coordinator'),
  ('production sound mixer'),
  ('production supervisor Second Unit Director or Assistant Director'),
  ('production supervisor'),
  ('projectionist'),
  ('property master'),
  ('propmaker foreman'),
  ('propmaker gang boss'),
  ('propmaker gang boss'),
  ('propman'),
  ('propshop foreman'),
  ('propshop foreman'),
  ('re-recording mixer'),
  ('re-recording mixer'),
  ('re-recording mixer'),
  ('recordist'),
  ('rigging best boy'),
  ('rigging electrician'),
  ('rigging electrician'),
  ('rigging electrician'),
  ('rigging gaffer'),
  ('rigging grip'),
  ('rigging grip'),
  ('rigging grip'),
  ('script supervisor'),
  ('script supervisor'),
  ('seamstress'),
  ('second assistant camera'),
  ('second assistant camera'),
  ('second assistant camera'),
  ('second assistant editor'),
  ('second rigging grip'),
  ('second second assistant director'),
  ('senior set designer'),
  ('set designer'),
  ('set dresser'),
  ('set dresser'),
  ('set dresser'),
  ('set estimator'),
  ('set production assistant'),
  ('set production assistant'),
  ('sound editor'),
  ('sound editor'),
  ('sound editor'),
  ('sound editor'),
  ('sound editor'),
  ('sound editor'),
  ('sound editor'),
  ('special effects Visual Effects by'),
  ('special thanks'),
  ('stand-by painter'),
  ('steadicam assistant Casting Department'),
  ('Steadicam operator'),
  ('still photographer'),
  ('storyboard consultant'),
  ('stunt coordinator'),
  ('stunt double: Tim Robbins Camera and Electrical Department'),
  ('stunts'),
  ('stunts'),
  ('stunts'),
  ('stunts'),
  ('stunts'),
  ('stunts'),
  ('stunts'),
  ('supervising sound editor'),
  ('technical director of sound'),
  ('temp boom operator'),
  ('thanks: assistant to the Warden of The Mansfield Correctional Institution'),
  ('thanks: Director of the U.S. Virgin Islands Film Commission'),
  ('thanks: Mansfield Convention & Visitors Bureau'),
  ('thanks: Ohio Film Commission'),
  ('thanks: Warden of The Mansfield Correctional Institution'),
  ('third assistant director Art Department'),
  ('transportation captain'),
  ('transportation coordinator'),
  ('unit production manager'),
  ('unit publicist'),
  ('video assist operator'),
  ('video assistant'),
  ('visual effects producer Stunts'),
  ('wardrobe assistant'),
  ('wardrobe supervisor');